# Generated by Django 3.0.4 on 2020-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_body',
            field=models.TextField(verbose_name='Article body'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=150, verbose_name='Article title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified on'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published on'),
        ),
    ]
